### Importation de la base de données

In [1]:
import os
from google.colab import drive
drive.mount('drive/')

Mounted at drive/

In [2]:
os.chdir('drive/My Drive/yzr/')

In [3]:
#importation des bibliotheque 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
#stocker la base dans la variable df
df = pd.read_excel('./Analyse campagne BS pour Sales ops.xlsx')

In [5]:
df.head()

,Campaign name,ID,Job title,City,Region,Country,Emails sent,Emails opened,Opening count,Response,Response qualification,Added in campaign,First time contacted
0,YZR_CDO_Marketplaces_FR_052021,1.0,E-Commerce - Directrice Commerciale,Paris,Ile-de-France,France,Email #2,NaN,NaN,NaN,NaN,2021-11-09 11:07:18,2021-11-12 20:04:33
1,YZR_CDO_Marketplaces_FR_052021,2.0,Data Engineer,Asnières-sur-Seine,Ile-de-France,France,Email #1,NaN,NaN,NaN,NaN,2021-07-16 17:41:33,2021-07-29 17:26:24
2,YZR_CDO_Marketplaces_FR_052021,3.0,Marketplace Hiring Manager,Lille,Hauts-de-France,France,Email #1,NaN,NaN,NaN,NaN,2021-11-16 16:40:40,2021-12-09 15:37:29
3,YZR_CDO_Marketplaces_FR_052021,4.0,Responsable opérations Data/ Head of Data Oper...,Lille,Hauts-de-France,France,Email #6,NaN,NaN,NaN,NaN,2021-11-05 11:14:57,2021-11-08 10:34:26
4,YZR_CDO_Marketplaces_FR_052021,5.0,Vice President eCommerce,NaN,NaN,Luxembourg,not contacted yet,NaN,NaN,NaN,NaN,2021-07-16 17:41:18,NaT

### exploration de la base

In [6]:
# pour voir le nombre de lignes et de colonne
df.shape

(5805, 13)

In [7]:
df.value_counts()

Campaign name                   ID      Job title                              City                  Region              Country         Emails sent  Emails opened               Opening count  Response              Response qualification                               Added in campaign    First time contacted
YZR_CDO_Marketplaces_FR_052021  22.0    Directeur Général                      Pauillac              New Aquitaine       France          Email #2     Email #2                    2.0            Understand objection  I am not interested in this solution / topic         2021-06-03 11:13:32  2021-06-10 19:43:48     1
                                27.0    e-Commerce / CRM Manager BeNeLux       Jette                 Brussels-Capital    Belgium         Email #2     Email #1,Email #2           4.0            Follow up later       This is not in our plans / not a priority right now  2022-01-17 18:11:25  2022-01-20 10:02:37     1
                                3172.0  Chef de projet E-commerce              Bondy                 Ile-de-France       France          Email #3     Email #1,Email #2,Email #3  4.0            Understand objection  I already have a partner                             2021-11-16 16:40:04  2021-11-30 10:47:22     1
                                3141.0  Managing Director ART BRUSSELS         Jette                 Brussels-Capital    Belgium         Email #3     Email #3                    2.0            Understand objection  I am not interested in this solution / topic         2021-06-03 11:13:14  2021-06-03 12:58:21     1
                                3124.0  Business Analyst E-commerce            Paris                 Ile-de-France       France          Email #5     Email #5                    1.0            Acknowledge           I forwarded your email to the person in charge       2021-11-16 16:47:41  2021-12-16 13:35:23     1
                                                                                                                                                                                                                                                                                                                        ..
                                1281.0  CRM & Data Manager                     Boulogne-Billancourt  Ile-de-France       France          Email #1     Email #2                    1.0            Understand objection  I already have a partner                             2021-10-22 15:52:07  2021-10-26 17:29:18     1
                                1244.0  Managing Director Scout24 Advertising  Wünnewil-Flamatt      Canton of Fribourg  Switzerland     Email #1     Email #1                    3.0            Understand objection  I already have a partner                             2021-06-03 11:13:30  2021-06-10 15:06:57     1
                                1231.0  Chef de projet en Data Gouvernance     Nantes                Pays de la Loire    France          Email #3     Email #1,Email #3           2.0            Understand objection  I already have a partner                             2021-11-16 16:40:28  2021-12-07 17:47:59     1
                                1221.0  Innovation Softw Engineer              Geneva                Geneva              Switzerland     Email #3     Email #1,Email #2,Email #3  4.0            Verify fit            I am not the right contact                           2021-09-14 11:47:20  2021-09-29 09:38:35     1
YZR_Ecommerce_ENG_022022        5604.0  Head Of Analytics                      London                England             United Kingdom  Email #2     Email #1,Email #2           4.0            Opt-out               Please remove me from your list                      2022-02-28 22:06:45  2022-03-09 12:41:26     1
Length: 120, dtype: int64

In [8]:
df['Emails sent']

0                Email #2
1                Email #1
2                Email #1
3                Email #6
4       not contacted yet
              ...
5800    not contacted yet
5801    not contacted yet
5802             Email #1
5803             Email #2
5804    not contacted yet
Name: Emails sent, Length: 5805, dtype: object

In [9]:
df['Response']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
5800    NaN
5801    NaN
5802    NaN
5803    NaN
5804    NaN
Name: Response, Length: 5805, dtype: object

In [10]:
df['Response'].value_counts()

Understand objection    69
Opt-out                 50
Follow up later         26
Acknowledge             23
Qualify                 22
Verify fit              21
Name: Response, dtype: int64

In [11]:
df['Response qualification']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
5800    NaN
5801    NaN
5802    NaN
5803    NaN
5804    NaN
Name: Response qualification, Length: 5805, dtype: object

In [12]:
df['Response qualification'].value_counts()

I am not interested in this solution / topic                                     46
Please remove me from your list                                                  41
I am not the right contact                                                       17
This is not in our plans / not a priority right now                              14
I forwarded your email to the person in charge                                   13
I am interested, let's have a meeting                                            11
I have an internal solution                                                      10
Try to contact this person instead                                                9
Stop writing me; this is spam                                                     8
I am not interested right now but I am keeping your information                   7
I am not the decision maker for this matter                                       6
I already have a partner                                                          6
I am interested but I don't have time; contact me again later                     4
I want to know more before to continue the conversation                           3
I am not interested right now but you can try again later                         3
I am interested, please tell me more                                              3
We have other priorities but maybe later                                          2
I am not sure what this is about                                                  2
This solution is not suitable for our company                                     2
Where did you get my email                                                        1
My team is interested, get in touch with them                                     1
GDPR                                                                              1
I am in charge of this topic but I am not interested in your product/solution     1
Name: Response qualification, dtype: int64

In [13]:
df['Added in campaign']

0      2021-11-09 11:07:18
1      2021-07-16 17:41:33
2      2021-11-16 16:40:40
3      2021-11-05 11:14:57
4      2021-07-16 17:41:18
               ...
5800   2022-03-21 19:01:54
5801   2022-02-05 02:13:25
5802   2022-02-05 03:01:10
5803   2022-03-21 18:30:47
5804   2022-03-21 19:06:00
Name: Added in campaign, Length: 5805, dtype: datetime64[ns]

In [14]:
df['Added in campaign'].value_counts()

2022-02-05 02:23:56    30
2022-02-28 22:15:21    29
2022-02-28 22:15:20    29
2022-02-28 22:05:34    29
2022-02-05 02:13:25    29
                       ..
2021-11-05 11:14:10     1
2021-11-05 11:14:51     1
2021-06-14 14:47:22     1
2021-11-05 11:13:56     1
2022-03-22 18:20:24     1
Name: Added in campaign, Length: 692, dtype: int64

In [15]:
# le pourcentage de valeurs NULL dans chaque colonne
df.isnull().sum()*100/5805

Campaign name              0.000000
ID                         0.000000
Job title                  0.757967
City                      18.863049
Region                    15.590009
Country                    1.998277
Emails sent                0.947459
Emails opened             71.403962
Opening count             71.403962
Response                  96.365202
Response qualification    96.365202
Added in campaign          0.999139
First time contacted      15.107666
dtype: float64

In [16]:
# suppression de la colonne Response 
del df['Response']

In [17]:
# suppression de la colonne Response qualification
del df ['Response qualification']

In [18]:
# suppression de la colonne Added in campaign
del df['Added in campaign']

### email sended

In [19]:
# importation de bibliothèque re  pour qu'on puisse utuliser Les expressions régulières
import re

In [20]:
# la fréquence de chaque valeur dans la colonne ' Email sent '
df['Emails sent'].value_counts()

Email #6             2560
Email #1              852
not contacted yet     806
Email #2              515
Email #4              413
Email #5              379
Email #3              225
Name: Emails sent, dtype: int64

In [21]:
# expressions régulière pour selectionner la chaine "Email #"  dans la colonne  Email sent
hashtag = re.compile(r"^(Email #)")

In [22]:
# remplacer la phrase " not contacted yet "  par des zeros  
df['Emails sent']= df['Emails sent'].replace("not contacted yet","0")

In [23]:
#supprimer la chaine 'Email #' dans chauque ligne 

df['Emails sent'] = df['Emails sent'].apply(lambda x : re.sub(hashtag,"",str(x)))

In [24]:
df['Emails sent']

0       2
1       1
2       1
3       6
4       0
       ..
5800    0
5801    0
5802    1
5803    2
5804    0
Name: Emails sent, Length: 5805, dtype: object

In [25]:
#remplacer les valeur null par -1
df['Emails sent'] = df['Emails sent'].apply(lambda x : x.replace('nan','-1'))

### Operation sur la colonne  Emails opened  #1

In [26]:
# expressions régulière pour selectionner la chaine "Email #"  

hashtag2 = re.compile(r"(Email #)")

In [27]:
# remplacer les valleur null par zero dans la colonne  Email opened
df['Emails opened'].fillna(0, inplace=True)

### Operation sur la colonne Opening count

In [28]:
# remplacer les valeur null par zero
df['Opening count'].fillna(0, inplace=True)

In [29]:
df['Opening count'].value_counts()

0.0     4145
1.0      552
2.0      349
3.0      194
4.0      158
6.0      122
5.0      121
7.0       60
8.0       42
9.0       13
10.0      11
11.0       8
13.0       5
12.0       5
14.0       4
18.0       3
15.0       3
16.0       2
17.0       2
30.0       1
23.0       1
19.0       1
21.0       1
20.0       1
25.0       1
Name: Opening count, dtype: int64

In [30]:
df['Emails opened']

0                       0
1                       0
2                       0
3                       0
4                       0
              ...
5800                    0
5801                    0
5802                    0
5803    Email #1,Email #2
5804                    0
Name: Emails opened, Length: 5805, dtype: object

In [31]:
# expressions régulière pour selectionner la chaine "Email #"  dans la colonne  Email opened
df['Emails opened'] = df['Emails opened'].apply(lambda x : re.sub(hashtag2,"",x) if x!=0 else x)

## Operation sur la colonne Emails opened #2

In [32]:
df

,Campaign name,ID,Job title,City,Region,Country,Emails sent,Emails opened,Opening count,First time contacted
0,YZR_CDO_Marketplaces_FR_052021,1.0,E-Commerce - Directrice Commerciale,Paris,Ile-de-France,France,2,0,0.0,2021-11-12 20:04:33
1,YZR_CDO_Marketplaces_FR_052021,2.0,Data Engineer,Asnières-sur-Seine,Ile-de-France,France,1,0,0.0,2021-07-29 17:26:24
2,YZR_CDO_Marketplaces_FR_052021,3.0,Marketplace Hiring Manager,Lille,Hauts-de-France,France,1,0,0.0,2021-12-09 15:37:29
3,YZR_CDO_Marketplaces_FR_052021,4.0,Responsable opérations Data/ Head of Data Oper...,Lille,Hauts-de-France,France,6,0,0.0,2021-11-08 10:34:26
4,YZR_CDO_Marketplaces_FR_052021,5.0,Vice President eCommerce,NaN,NaN,Luxembourg,0,0,0.0,NaT
...,...,...,...,...,...,...,...,...,...,...
5800,YZR_Ecommerce_ENG_022022,5801.0,eCommerce Marketing Manager,Amsterdam,Noord-Holland,Netherlands,0,0,0.0,NaT
5801,YZR_Ecommerce_ENG_022022,5802.0,Lead Data Architect,Taunton,England,United Kingdom,0,0,0.0,NaT
5802,YZR_Ecommerce_ENG_022022,5803.0,Ecommerce Manager,Bristol,England,United Kingdom,1,0,0.0,2022-02-25 10:08:25
5803,YZR_Ecommerce_ENG_022022,5804.0,Senior Ecommerce Product Manager,London,England,United Kingdom,2,"1,2",8.0,2022-03-30 15:35:44
5804,YZR_Ecommerce_ENG_022022,5805.0,Facility Manager Warehouse Albert Heijn eCommerce,Bergen,North Holland,Netherlands,0,0,0.0,NaT

In [33]:
df['Emails opened']

0         0
1         0
2         0
3         0
4         0
       ...
5800      0
5801      0
5802      0
5803    1,2
5804      0
Name: Emails opened, Length: 5805, dtype: object

In [34]:
# convertir  les colonne qui contient plusieur mail ouvert  en liste 
df['Emails opened']= df['Emails opened'].apply(lambda x : str(x).split(","))

In [35]:
#une colone pour chaque chaque email  
df_opend_mail=pd.DataFrame(df['Emails opened'].to_list(),index=df['Emails opened'].index,columns=['Email_1_opened','Email_2_opened','Email_3_opened','Email_4_opened','Email_5_opened','Email_6_opened'])

In [36]:
# data frae qui contien les email opend  avec des columns 
df_opend_mail

,Email_1_opened,Email_2_opened,Email_3_opened,Email_4_opened,Email_5_opened,Email_6_opened
0,0,None,None,None,None,None
1,0,None,None,None,None,None
2,0,None,None,None,None,None
3,0,None,None,None,None,None
4,0,None,None,None,None,None
...,...,...,...,...,...,...
5800,0,None,None,None,None,None
5801,0,None,None,None,None,None
5802,0,None,None,None,None,None
5803,1,2,None,None,None,None
5804,0,None,None,None,None,None

In [37]:
# remplacer les nan par des zero 
df_opend_mail.fillna(0, inplace=True)

In [38]:
df_opend_mail

,Email_1_opened,Email_2_opened,Email_3_opened,Email_4_opened,Email_5_opened,Email_6_opened
0,0,0,0,0,0,0
1,0,0,0,0,0,0
2,0,0,0,0,0,0
3,0,0,0,0,0,0
4,0,0,0,0,0,0
...,...,...,...,...,...,...
5800,0,0,0,0,0,0
5801,0,0,0,0,0,0
5802,0,0,0,0,0,0
5803,1,2,0,0,0,0
5804,0,0,0,0,0,0

In [39]:
#transfomer le type en int
df_opend_mail= df_opend_mail.astype(int)

In [40]:
df_opend_mail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5805 entries, 0 to 5804
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Email_1_opened  5805 non-null   int64
 1   Email_2_opened  5805 non-null   int64
 2   Email_3_opened  5805 non-null   int64
 3   Email_4_opened  5805 non-null   int64
 4   Email_5_opened  5805 non-null   int64
 5   Email_6_opened  5805 non-null   int64
dtypes: int64(6)
memory usage: 272.2 KB

In [41]:
# remplacer les chiffre qui sont > 1  par 1
df_opend_mail[df_opend_mail >1 ] = 1
df_opend_mail.reset_index()

,index,Email_1_opened,Email_2_opened,Email_3_opened,Email_4_opened,Email_5_opened,Email_6_opened
0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0
2,2,0,0,0,0,0,0
3,3,0,0,0,0,0,0
4,4,0,0,0,0,0,0
...,...,...,...,...,...,...,...
5800,5800,0,0,0,0,0,0
5801,5801,0,0,0,0,0,0
5802,5802,0,0,0,0,0,0
5803,5803,1,1,0,0,0,0
5804,5804,0,0,0,0,0,0

In [42]:
# concatination des deux table 
df=pd.concat([df,df_opend_mail],axis=1)

In [43]:
df

,Campaign name,ID,Job title,City,Region,Country,Emails sent,Emails opened,Opening count,First time contacted,Email_1_opened,Email_2_opened,Email_3_opened,Email_4_opened,Email_5_opened,Email_6_opened
0,YZR_CDO_Marketplaces_FR_052021,1.0,E-Commerce - Directrice Commerciale,Paris,Ile-de-France,France,2,[0],0.0,2021-11-12 20:04:33,0,0,0,0,0,0
1,YZR_CDO_Marketplaces_FR_052021,2.0,Data Engineer,Asnières-sur-Seine,Ile-de-France,France,1,[0],0.0,2021-07-29 17:26:24,0,0,0,0,0,0
2,YZR_CDO_Marketplaces_FR_052021,3.0,Marketplace Hiring Manager,Lille,Hauts-de-France,France,1,[0],0.0,2021-12-09 15:37:29,0,0,0,0,0,0
3,YZR_CDO_Marketplaces_FR_052021,4.0,Responsable opérations Data/ Head of Data Oper...,Lille,Hauts-de-France,France,6,[0],0.0,2021-11-08 10:34:26,0,0,0,0,0,0
4,YZR_CDO_Marketplaces_FR_052021,5.0,Vice President eCommerce,NaN,NaN,Luxembourg,0,[0],0.0,NaT,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5800,YZR_Ecommerce_ENG_022022,5801.0,eCommerce Marketing Manager,Amsterdam,Noord-Holland,Netherlands,0,[0],0.0,NaT,0,0,0,0,0,0
5801,YZR_Ecommerce_ENG_022022,5802.0,Lead Data Architect,Taunton,England,United Kingdom,0,[0],0.0,NaT,0,0,0,0,0,0
5802,YZR_Ecommerce_ENG_022022,5803.0,Ecommerce Manager,Bristol,England,United Kingdom,1,[0],0.0,2022-02-25 10:08:25,0,0,0,0,0,0
5803,YZR_Ecommerce_ENG_022022,5804.0,Senior Ecommerce Product Manager,London,England,United Kingdom,2,"[1, 2]",8.0,2022-03-30 15:35:44,1,1,0,0,0,0
5804,YZR_Ecommerce_ENG_022022,5805.0,Facility Manager Warehouse Albert Heijn eCommerce,Bergen,North Holland,Netherlands,0,[0],0.0,NaT,0,0,0,0,0,0

In [44]:
# supprission de la colonne ID
del df['ID']

In [45]:
# supprission de la colonne  Emails opened 
del df ['Emails opened']

In [46]:
df

,Campaign name,Job title,City,Region,Country,Emails sent,Opening count,First time contacted,Email_1_opened,Email_2_opened,Email_3_opened,Email_4_opened,Email_5_opened,Email_6_opened
0,YZR_CDO_Marketplaces_FR_052021,E-Commerce - Directrice Commerciale,Paris,Ile-de-France,France,2,0.0,2021-11-12 20:04:33,0,0,0,0,0,0
1,YZR_CDO_Marketplaces_FR_052021,Data Engineer,Asnières-sur-Seine,Ile-de-France,France,1,0.0,2021-07-29 17:26:24,0,0,0,0,0,0
2,YZR_CDO_Marketplaces_FR_052021,Marketplace Hiring Manager,Lille,Hauts-de-France,France,1,0.0,2021-12-09 15:37:29,0,0,0,0,0,0
3,YZR_CDO_Marketplaces_FR_052021,Responsable opérations Data/ Head of Data Oper...,Lille,Hauts-de-France,France,6,0.0,2021-11-08 10:34:26,0,0,0,0,0,0
4,YZR_CDO_Marketplaces_FR_052021,Vice President eCommerce,NaN,NaN,Luxembourg,0,0.0,NaT,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5800,YZR_Ecommerce_ENG_022022,eCommerce Marketing Manager,Amsterdam,Noord-Holland,Netherlands,0,0.0,NaT,0,0,0,0,0,0
5801,YZR_Ecommerce_ENG_022022,Lead Data Architect,Taunton,England,United Kingdom,0,0.0,NaT,0,0,0,0,0,0
5802,YZR_Ecommerce_ENG_022022,Ecommerce Manager,Bristol,England,United Kingdom,1,0.0,2022-02-25 10:08:25,0,0,0,0,0,0
5803,YZR_Ecommerce_ENG_022022,Senior Ecommerce Product Manager,London,England,United Kingdom,2,8.0,2022-03-30 15:35:44,1,1,0,0,0,0
5804,YZR_Ecommerce_ENG_022022,Facility Manager Warehouse Albert Heijn eCommerce,Bergen,North Holland,Netherlands,0,0.0,NaT,0,0,0,0,0,0

### changement du nom des Campaign

In [47]:
df['Campaign name'].value_counts()

YZR_CDO_Marketplaces_FR_052021    3934
YZR_Ecommerce_ENG_022022          1871
Name: Campaign name, dtype: int64

In [48]:
df.rename(columns = {'YZR_CDO_Marketplaces_FR_052021':'CDO_Marketplaces', 'YZR_Ecommerce_ENG_022022':'Ecommerce_ENG'}, inplace = True)

In [49]:
# voie le nombre de campaign 
df['Campaign name'].value_counts()

YZR_CDO_Marketplaces_FR_052021    3934
YZR_Ecommerce_ENG_022022          1871
Name: Campaign name, dtype: int64

In [50]:
#renomer la comaign   YZR_Ecommerce_ENG_022022 ----> Ecommerce ENG

df['Campaign name']=df['Campaign name'].apply(lambda x : x.replace("YZR_Ecommerce_ENG_022022","Ecommerce ENG"))

In [51]:
#renomer la comaign   YZR_CDO_Marketplaces_FR_052021 ----> CDO Marketplaces FR
df['Campaign name'] = df['Campaign name'].apply(lambda x : x.replace('YZR_CDO_Marketplaces_FR_052021','CDO Marketplaces FR'))

In [52]:
df

,Campaign name,Job title,City,Region,Country,Emails sent,Opening count,First time contacted,Email_1_opened,Email_2_opened,Email_3_opened,Email_4_opened,Email_5_opened,Email_6_opened
0,CDO Marketplaces FR,E-Commerce - Directrice Commerciale,Paris,Ile-de-France,France,2,0.0,2021-11-12 20:04:33,0,0,0,0,0,0
1,CDO Marketplaces FR,Data Engineer,Asnières-sur-Seine,Ile-de-France,France,1,0.0,2021-07-29 17:26:24,0,0,0,0,0,0
2,CDO Marketplaces FR,Marketplace Hiring Manager,Lille,Hauts-de-France,France,1,0.0,2021-12-09 15:37:29,0,0,0,0,0,0
3,CDO Marketplaces FR,Responsable opérations Data/ Head of Data Oper...,Lille,Hauts-de-France,France,6,0.0,2021-11-08 10:34:26,0,0,0,0,0,0
4,CDO Marketplaces FR,Vice President eCommerce,NaN,NaN,Luxembourg,0,0.0,NaT,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5800,Ecommerce ENG,eCommerce Marketing Manager,Amsterdam,Noord-Holland,Netherlands,0,0.0,NaT,0,0,0,0,0,0
5801,Ecommerce ENG,Lead Data Architect,Taunton,England,United Kingdom,0,0.0,NaT,0,0,0,0,0,0
5802,Ecommerce ENG,Ecommerce Manager,Bristol,England,United Kingdom,1,0.0,2022-02-25 10:08:25,0,0,0,0,0,0
5803,Ecommerce ENG,Senior Ecommerce Product Manager,London,England,United Kingdom,2,8.0,2022-03-30 15:35:44,1,1,0,0,0,0
5804,Ecommerce ENG,Facility Manager Warehouse Albert Heijn eCommerce,Bergen,North Holland,Netherlands,0,0.0,NaT,0,0,0,0,0,0

### Expotation du fichier

In [53]:
# exporter le résultat dans drive sous format csv
df.to_csv("/content/drive/MyDrive/yzr/Analyse_campagne.csv", index=False)